package dar.member.entity; // Defines the package where this class belongs

import java.util.ArrayList;
import java.util.List;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;

/**
 * Represents an Chapter entity in the pet store system. This class is mapped
 * to a database table using JPA annotations.
 */
@Entity // Marks this class as a JPA entity, mapping it to a database table
@Data // Lombok annotation to automatically generate getter, setter, equals, hashCode,
		// and toString methods
public class Chapter {

	@Id // Marks this field as the primary key
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	// Specifies that the primary key will be auto-generated by the database using
	// an identity column
	private Long chapterId; // Unique identifier for an chapter
	private String chapterName; // First name of the chapter
	private String chapterNumber; // Last name of the chapter
	
	@OneToMany(mappedBy = "chapter", cascade = CascadeType.ALL, orphanRemoval = true)
	private List<Member> members = new ArrayList<>();

//	// Excludes  field from equals() and hashCode() methods to prevent circular
//	// dependencies
//	@EqualsAndHashCode.Exclude 
//	@ToString.Exclude // Excludes this field from the toString() method to prevent infinite loops
//	@ManyToOne(cascade = CascadeType.ALL)
//	// Defines a many-to-one relationship with the Member entity.
//	// - Many chapter belong to one pet store.
//	// - CascadeType.ALL ensures that any changes to an Chapter (persist, merge,
//	// remove, etc.) also affect the associated Member.
//	@JoinColumn(name = "member_id")
//	// Specifies the foreign key column in the Chapter table that references the
//	// Member entity
//	private Member member; // Reference to the associated pet store
}
